### PR TITLE
Cyrillics and Latin Update

### PR DESCRIPTION
**Pull request by StefanPeev**

### CODE REVIEW

**Comment by StefanPeev** [comment]
@ms-studio There is still a lot off work to be done, but, please, check my proposals for Cyrillic script and some updates in the Latin script.

**Comment by StefanPeev** [comment]
karmilla_01
karmilla-regular-26-01-2018-01

**Comment by ms-studio** [comment]
Hi Stefan, thanks for your work! It looks great to me, but I cannot really judge the quality of the cyrillic. It would be interesting to get feedback from @alexeiva.

Also, you could post a thread on https://groups.google.com/group/googlefonts-discuss about this cyrillic addition.

**Comment by StefanPeev** [comment]
@ms-studio @alexeiva The Cyrillic is still not in its final edition. So, there will be another PR from me. But I think there is a sense the Cyrillic script to be merged in Karmilla even in its first edition - just to start the process...

**Comment by ms-studio** [comment]
Yes, that's also what I think – so I just merged it, in order to make it easier to review.

**Comment by alexeiva** [comment]
Gentlemen, I am not in a position to review this thoroughly. I suggest you ask for advice on forums such as typedrawers. Compare with fonts like Nunito Sans, PT Sans etc. 

On a quick look this requires a lot more work before it can be used. Issues with proportions, drawing. To name a few:

- `б` top pennant (~-part) too thick. 
- `з` out of balance in both ru and bgr styles
- `У`  too narrow
- coordinate descenders, соmpare Д and д
- `ы` needs more whitespace inside.
- coordinate bowls in ВБЬЪЫ(Б has a tiny bowl)
- `Ю` squeezed inner white.
...

**Comment by StefanPeev** [comment]
I also said it was too early the Cyrillic project to be discussed (even in Typedrawers) - the Cyrillic is still not in its final edition.

**Comment by andrewshadura** [comment]
WOOOOW YOU DID IT :smile:

**Comment by andrewshadura** [comment]
@StefanPeev, a comment from me on the style: I think the capital `У` needs the diagonal line to be possibly more steep and with a hook below, to match the style of the lower case `у`.

**Comment by StefanPeev** [comment]
@andrewshadura Thank you for your remark. It's still the first draft of the Cyrillic script in Karmilla and it's far from beening perfect...

**Pull request merged**
