### PR TITLE
Add glyphs: Ľ, ľ

### PR DESCRIPTION
**Pull request by andrewshadura**

### CODE REVIEW

**Comment by ms-studio** [comment]
Thanks @andrewshadura for this addition! Can you let us know what language is benefitting from this improvement?

**Comment by andrewshadura** [comment]
Slovak.

**Comment by nclm** [comment]
A story about Ľ: https://www.typotheque.com/articles/lcaron :)

**Comment by andrewshadura** [comment]
@nclm  :+1:

**Comment by ms-studio** [comment]
Thanks – also for the great story you linked to!

**Pull request merged**
